apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../crd
- ../../rbac
- ../../manager

namespace: tssc-operator-system
namePrefix: tssc-operator-

images:
- name: testing
  newName: quay.io/dwinchell_redhat/tssc-operator

patchesStrategicMerge:
- ../manager_image.yaml
- ../debug_logs_patch.yaml
- ../pull_policy/Always.yaml
